version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/ngstack-core

    steps:
      - checkout

      - restore_cache:
          key: ngstack-core-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: ngstack-core-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: npm run spellcheck
      - run: xvfb-run -a npm test -- translate --watch=false
      - run: xvfb-run -a npm test -- code-editor --watch=false
      - run: xvfb-run -a npm test -- electron --watch=false
