name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - name: Build and Test
      run: |
        npm ci
        npm run lint --format=stylish
        npm run spellcheck
        npm run  format:check
        npm run test:ci
        npm run build
        npm run size
      env:
        CI: true
